name: smoke_tests
on: [push]
jobs:
    run-smoke-tests:
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt-get install iverilog
            - run: cd ../../; ./flow.sh sim
              name: Run core's unit test suite
              shell: bash
